apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sbgcrun-frontend
  annotations:
    # 5章Step3でコメントアウト予定
    # run.googleapis.com/ingress: all
    run.googleapis.com/invoker-iam-disabled: "true"
    run.googleapis.com/maxScale: "10"
    # 5章Step3でコメントを外す。外部からはロードバランサ経由のみを許可する
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    # 6章Step1でコメントを外す。デフォルトURLを無効化する
    # run.googleapis.com/default-url-disabled: "true"
    # 6章Step9でコメントを外す。BinaryAuthの有効化
    # run.googleapis.com/binary-authorization: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/execution-environment: gen2
        # 5章Step4でコメントを外す。VPCネットワークの設定
        run.googleapis.com/network-interfaces: '[{"network":"sbgcrun-app", "subnetwork":"sbgcrun-app"}]'
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      containerConcurrency: 40
      timeoutSeconds: 300
      serviceAccountName: sbgcrun-app-frontend@project-5a711c3e-5949-4e62-ac0.iam.gserviceaccount.com
      containers:
      - image: frontend
        env:
          - name: BACKEND_URL
            # value: "https://sbgcrun-backend-xxxxx.asia-northeast1.run.app" # FIXME: Change BACKEND_URL value after backend resources is created
            value: "https://sbgcrun-backend-216158901315.asia-northeast1.run.app"
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 2
          failureThreshold: 60
          tcpSocket:
            port: 8080
